2018-05-04T08:51:46.860Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Fri May 04 2018 14:21:46 GMT+0530 (India Standard Time), pid=7596, uid=null, gid=null, cwd=D:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, D:\Node_JavaScript\Node-Sample\app.js], rss=33075200, heapTotal=15024128, heapUsed=11935032, external=17908128, loadavg=[0, 0, 0], uptime=71785.7293422, trace=[column=11, file=D:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=505, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=D:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=329, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=D:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=245, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (D:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js:505:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (D:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js:329:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (D:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js:245:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13)]
2018-05-08T06:28:51.785Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 08 2018 11:58:51 GMT+0530 (India Standard Time), pid=8212, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=33136640, heapTotal=14499840, heapUsed=11926760, external=17908128, loadavg=[0, 0, 0], uptime=80973.6527405, trace=[column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=505, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=329, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=245, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js:505:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js:329:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js:245:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13)]
2018-05-08T06:30:51.746Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 08 2018 12:00:51 GMT+0530 (India Standard Time), pid=8212, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=33865728, heapTotal=14499840, heapUsed=12260768, external=17908152, loadavg=[0, 0, 0], uptime=81093.6157405, trace=[column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=505, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=329, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=245, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js:505:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js:329:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js:245:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13)]
2018-05-08T06:32:51.751Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 08 2018 12:02:51 GMT+0530 (India Standard Time), pid=8212, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=34144256, heapTotal=15024128, heapUsed=12501008, external=17916344, loadavg=[0, 0, 0], uptime=81213.6217405, trace=[column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=505, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=329, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=245, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js:505:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js:329:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js:245:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13)]
2018-05-08T06:37:00.655Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 08 2018 12:07:00 GMT+0530 (India Standard Time), pid=8212, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=33615872, heapTotal=15024128, heapUsed=11986424, external=17916344, loadavg=[0, 0, 0], uptime=81462.5247405, trace=[column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=505, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=329, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=245, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js:505:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js:329:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js:245:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13)]
2018-05-08T06:39:00.646Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue May 08 2018 12:09:00 GMT+0530 (India Standard Time), pid=8212, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=33673216, heapTotal=15024128, heapUsed=12006168, external=17924536, loadavg=[0, 0, 0], uptime=81582.5177405, trace=[column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=505, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=329, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=245, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\topologies\server.js:505:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\pool.js:329:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (d:\Node_JavaScript\Node-Sample\node_modules\mongodb-core\lib\connection\connection.js:245:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13)]
2018-05-08T09:20:45.394Z - error: uncaughtException: Identifier 'dbConfig' has already been declared date=Tue May 08 2018 14:50:45 GMT+0530 (India Standard Time), pid=10236, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=32555008, heapTotal=18694144, heapUsed=11326792, external=287321, loadavg=[0, 0, 0], uptime=91287.2634005, trace=[column=10, file=vm.js, function=createScript, line=80, method=null, native=false, column=10, file=vm.js, function=Object.runInThisContext, line=139, method=runInThisContext, native=false, column=28, file=module.js, function=Module._compile, line=616, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=22, file=d:\Node_JavaScript\Node-Sample\routes\routes.js, function=module.exports, line=2, method=exports, native=false], stack=[d:\Node_JavaScript\Node-Sample\controllers\controller.js:5, const dbConfig = require('../Utilities.js');,       ^, , SyntaxError: Identifier 'dbConfig' has already been declared,     at createScript (vm.js:80:10),     at Object.runInThisContext (vm.js:139:10),     at Module._compile (module.js:616:28),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at module.exports (d:\Node_JavaScript\Node-Sample\routes\routes.js:2:22)]
2018-05-08T09:22:14.094Z - error: uncaughtException: Cannot find module '../Utilities.js' date=Tue May 08 2018 14:52:14 GMT+0530 (India Standard Time), pid=8524, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=38277120, heapTotal=21315584, heapUsed=11819304, external=17885607, loadavg=[0, 0, 0], uptime=91375.9622695, trace=[column=15, file=module.js, function=Module._resolveFilename, line=547, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=474, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=19, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=5, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false], stack=[Error: Cannot find module '../Utilities.js',     at Function.Module._resolveFilename (module.js:547:15),     at Function.Module._load (module.js:474:25),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\controllers\controller.js:5:19),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3)]
2018-05-08T09:22:33.012Z - error: uncaughtException: Cannot find module '../Utilities.js' date=Tue May 08 2018 14:52:32 GMT+0530 (India Standard Time), pid=9748, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=38514688, heapTotal=22888448, heapUsed=11825400, external=17885607, loadavg=[0, 0, 0], uptime=91394.8801611, trace=[column=15, file=module.js, function=Module._resolveFilename, line=547, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=474, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=19, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=5, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false], stack=[Error: Cannot find module '../Utilities.js',     at Function.Module._resolveFilename (module.js:547:15),     at Function.Module._load (module.js:474:25),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\controllers\controller.js:5:19),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3)]
2018-05-08T09:23:28.928Z - error: uncaughtException: Cannot find module 'd:\Node_JavaScript\Node-SampleUtilities/utilities.js' date=Tue May 08 2018 14:53:28 GMT+0530 (India Standard Time), pid=11144, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=38281216, heapTotal=21839872, heapUsed=12045184, external=17885607, loadavg=[0, 0, 0], uptime=91450.7957521, trace=[column=15, file=module.js, function=Module._resolveFilename, line=547, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=474, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=19, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=5, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false], stack=[Error: Cannot find module 'd:\Node_JavaScript\Node-SampleUtilities/utilities.js',     at Function.Module._resolveFilename (module.js:547:15),     at Function.Module._load (module.js:474:25),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\controllers\controller.js:5:19),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3)]
2018-05-08T09:23:47.404Z - error: uncaughtException: Cannot find module 'jsonwebtoken' date=Tue May 08 2018 14:53:47 GMT+0530 (India Standard Time), pid=2868, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=38219776, heapTotal=21315584, heapUsed=11993360, external=17885607, loadavg=[0, 0, 0], uptime=91469.2725996, trace=[column=15, file=module.js, function=Module._resolveFilename, line=547, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=474, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=null, line=4, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false], stack=[Error: Cannot find module 'jsonwebtoken',     at Function.Module._resolveFilename (module.js:547:15),     at Function.Module._load (module.js:474:25),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:4:11),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3)]
2018-05-08T09:24:55.358Z - error: uncaughtException: Cannot find module 'jsonwebtoken' date=Tue May 08 2018 14:54:55 GMT+0530 (India Standard Time), pid=8580, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=38232064, heapTotal=20267008, heapUsed=13962560, external=18585844, loadavg=[0, 0, 0], uptime=91537.2253942, trace=[column=15, file=module.js, function=Module._resolveFilename, line=547, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=474, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=null, line=4, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false], stack=[Error: Cannot find module 'jsonwebtoken',     at Function.Module._resolveFilename (module.js:547:15),     at Function.Module._load (module.js:474:25),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:4:11),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3)]
2018-05-08T09:52:08.708Z - error: uncaughtException: Cannot find module 'mongoose-unique-validator' date=Tue May 08 2018 15:22:08 GMT+0530 (India Standard Time), pid=9244, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=45445120, heapTotal=32325632, heapUsed=16080272, external=18843413, loadavg=[0, 0, 0], uptime=93170.5760723, trace=[column=15, file=module.js, function=Module._resolveFilename, line=547, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=474, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=23, file=d:\Node_JavaScript\Node-Sample\models\usermodel.js, function=null, line=3, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=505, method=null, native=false, column=3, file=module.js, function=Module._load, line=497, method=_load, native=false, column=17, file=module.js, function=Module.require, line=596, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=13, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=6, method=null, native=false, column=30, file=module.js, function=Module._compile, line=652, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=663, method=.js, native=false, column=32, file=module.js, function=Module.load, line=565, method=load, native=false], stack=[Error: Cannot find module 'mongoose-unique-validator',     at Function.Module._resolveFilename (module.js:547:15),     at Function.Module._load (module.js:474:25),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\models\usermodel.js:3:23),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32),     at tryModuleLoad (module.js:505:12),     at Function.Module._load (module.js:497:3),     at Module.require (module.js:596:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (d:\Node_JavaScript\Node-Sample\controllers\controller.js:6:13),     at Module._compile (module.js:652:30),     at Object.Module._extensions..js (module.js:663:10),     at Module.load (module.js:565:32)]
2018-05-08T11:47:32.829Z - error: uncaughtException: Cipher data must be a string or a buffer date=Tue May 08 2018 17:17:32 GMT+0530 (India Standard Time), pid=9460, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=38371328, heapTotal=19218432, heapUsed=15855984, external=17908647, loadavg=[0, 0, 0], uptime=100094.6984229, trace=[column=26, file=crypto.js, function=Cipher.update, line=170, method=update, native=false, column=22, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=Object.exports.encrypt, line=7, method=encrypt, native=false, column=45, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=149, method=null, native=false, column=17, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=result, line=414, method=null, native=false, column=9, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=270, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=connectCallback, line=944, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=801, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=131, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[TypeError: Cipher data must be a string or a buffer,     at Cipher.update (crypto.js:170:26),     at Object.exports.encrypt (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:7:22),     at d:\Node_JavaScript\Node-Sample\controllers\controller.js:149:45,     at result (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:406:9),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:270:5,     at connectCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:944:5),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:801:11,     at _combinedTickCallback (internal/process/next_tick.js:131:7),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-05-08T11:47:51.412Z - error: uncaughtException: Cipher data must be a string or a buffer date=Tue May 08 2018 17:17:51 GMT+0530 (India Standard Time), pid=9460, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=39149568, heapTotal=19218432, heapUsed=16004952, external=17917446, loadavg=[0, 0, 0], uptime=100113.2824229, trace=[column=26, file=crypto.js, function=Cipher.update, line=170, method=update, native=false, column=22, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=Object.exports.encrypt, line=7, method=encrypt, native=false, column=45, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=149, method=null, native=false, column=17, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=result, line=414, method=null, native=false, column=9, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=270, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=connectCallback, line=944, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=801, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=131, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[TypeError: Cipher data must be a string or a buffer,     at Cipher.update (crypto.js:170:26),     at Object.exports.encrypt (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:7:22),     at d:\Node_JavaScript\Node-Sample\controllers\controller.js:149:45,     at result (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:406:9),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:270:5,     at connectCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:944:5),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:801:11,     at _combinedTickCallback (internal/process/next_tick.js:131:7),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-05-08T11:48:51.682Z - error: uncaughtException: Cipher data must be a string or a buffer date=Tue May 08 2018 17:18:51 GMT+0530 (India Standard Time), pid=9460, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=39530496, heapTotal=19218432, heapUsed=16339728, external=17917965, loadavg=[0, 0, 0], uptime=100173.5534229, trace=[column=26, file=crypto.js, function=Cipher.update, line=170, method=update, native=false, column=22, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=Object.exports.encrypt, line=7, method=encrypt, native=false, column=45, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=149, method=null, native=false, column=17, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=result, line=414, method=null, native=false, column=9, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=270, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=connectCallback, line=944, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=801, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=131, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[TypeError: Cipher data must be a string or a buffer,     at Cipher.update (crypto.js:170:26),     at Object.exports.encrypt (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:7:22),     at d:\Node_JavaScript\Node-Sample\controllers\controller.js:149:45,     at result (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:406:9),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:270:5,     at connectCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:944:5),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:801:11,     at _combinedTickCallback (internal/process/next_tick.js:131:7),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-05-08T11:49:05.047Z - error: uncaughtException: Cipher data must be a string or a buffer date=Tue May 08 2018 17:19:05 GMT+0530 (India Standard Time), pid=9460, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=39436288, heapTotal=19742720, heapUsed=16215776, external=17919372, loadavg=[0, 0, 0], uptime=100186.9184229, trace=[column=26, file=crypto.js, function=Cipher.update, line=170, method=update, native=false, column=22, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=Object.exports.encrypt, line=7, method=encrypt, native=false, column=45, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=149, method=null, native=false, column=17, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=result, line=414, method=null, native=false, column=9, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=270, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=connectCallback, line=944, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=801, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=131, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[TypeError: Cipher data must be a string or a buffer,     at Cipher.update (crypto.js:170:26),     at Object.exports.encrypt (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:7:22),     at d:\Node_JavaScript\Node-Sample\controllers\controller.js:149:45,     at result (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:406:9),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:270:5,     at connectCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:944:5),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:801:11,     at _combinedTickCallback (internal/process/next_tick.js:131:7),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-05-08T11:49:10.063Z - error: uncaughtException: Cipher data must be a string or a buffer date=Tue May 08 2018 17:19:10 GMT+0530 (India Standard Time), pid=9460, uid=null, gid=null, cwd=d:\Node_JavaScript\Node-Sample, execPath=C:\Program Files\nodejs\node.exe, version=v8.11.1, argv=[C:\Program Files\nodejs\node.exe, d:\Node_JavaScript\Node-Sample\app.js], rss=39784448, heapTotal=19742720, heapUsed=16564528, external=17919891, loadavg=[0, 0, 0], uptime=100191.9324229, trace=[column=26, file=crypto.js, function=Cipher.update, line=170, method=update, native=false, column=22, file=d:\Node_JavaScript\Node-Sample\Utilities\utilities.js, function=Object.exports.encrypt, line=7, method=encrypt, native=false, column=45, file=d:\Node_JavaScript\Node-Sample\controllers\controller.js, function=null, line=149, method=null, native=false, column=17, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=result, line=414, method=null, native=false, column=9, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=270, method=null, native=false, column=5, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=connectCallback, line=944, method=null, native=false, column=11, file=d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js, function=null, line=801, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=131, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[TypeError: Cipher data must be a string or a buffer,     at Cipher.update (crypto.js:170:26),     at Object.exports.encrypt (d:\Node_JavaScript\Node-Sample\Utilities\utilities.js:7:22),     at d:\Node_JavaScript\Node-Sample\controllers\controller.js:149:45,     at result (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\utils.js:406:9),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:270:5,     at connectCallback (d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:944:5),     at d:\Node_JavaScript\Node-Sample\node_modules\mongodb\lib\mongo_client.js:801:11,     at _combinedTickCallback (internal/process/next_tick.js:131:7),     at process._tickCallback (internal/process/next_tick.js:180:9)]
